"""New Migration

Revision ID: 315af3be4944
Revises: af2d516f45cf
Create Date: 2022-11-27 16:06:44.653510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '315af3be4944'
down_revision = 'af2d516f45cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
