"""New column

Revision ID: 3beb90b52cb4
Revises: 556a932616fc
Create Date: 2022-11-28 19:19:30.074566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3beb90b52cb4'
down_revision = '556a932616fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
