"""New column

Revision ID: 556a932616fc
Revises: cdc90b0ec849
Create Date: 2022-11-28 18:21:49.224686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '556a932616fc'
down_revision = 'cdc90b0ec849'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_', sa.Column('contact_id', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_', 'contact_id')
    # ### end Alembic commands ###
