"""empty message

Revision ID: 6ad106a4df2e
Revises: 3beb90b52cb4
Create Date: 2022-12-01 18:55:10.482892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ad106a4df2e'
down_revision = '3beb90b52cb4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
