"""Unique added to username in user table

Revision ID: 850fd7442248
Revises: c043d5ca18d7
Create Date: 2022-11-27 16:38:52.136098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '850fd7442248'
down_revision = 'c043d5ca18d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
