"""New column

Revision ID: 92877f9ecd12
Revises: 850fd7442248
Create Date: 2022-11-28 17:59:34.095974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92877f9ecd12'
down_revision = '850fd7442248'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_', sa.Column('contact_id', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_', 'contact_id')
    # ### end Alembic commands ###
