"""Unique added to username in user table

Revision ID: c92998b41969
Revises: 315af3be4944
Create Date: 2022-11-27 16:08:55.365257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c92998b41969'
down_revision = '315af3be4944'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_', type_='unique')
    # ### end Alembic commands ###
