"""New column

Revision ID: cdc90b0ec849
Revises: bf30d844ebb6
Create Date: 2022-11-28 18:19:45.763394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdc90b0ec849'
down_revision = 'bf30d844ebb6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_', sa.Column('contact_id', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_', 'contact_id')
    # ### end Alembic commands ###
