"""First commit

Revision ID: 8e4205f669e4
Revises: 
Create Date: 2022-11-28 16:45:58.416616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e4205f669e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Conctact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telephone', sa.Integer(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=False),
    sa.Column('shared', sa.ARRAY(sa.Integer()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Conctact_id'), 'Conctact', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Conctact_id'), table_name='Conctact')
    op.drop_table('Conctact')
    # ### end Alembic commands ###
