"""First commit

Revision ID: 9107eec8c64f
Revises: 8e4205f669e4
Create Date: 2022-11-28 16:46:21.258485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9107eec8c64f'
down_revision = '8e4205f669e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
