"""New column

Revision ID: e2abfdc3a354
Revises: 9107eec8c64f
Create Date: 2022-11-29 17:50:08.303953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2abfdc3a354'
down_revision = '9107eec8c64f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
